# Generated by Django 6.0 on 2025-12-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0006_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(default='chat', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='uploaded_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='bot_reply',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user_message',
            field=models.TextField(blank=True),
        ),
    ]
