# Generated by Django 6.0 on 2025-12-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0007_chatmessage_message_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('document', 'Document')], default='text', max_length=10),
        ),
    ]
