# Generated by Django 6.0 on 2025-12-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0008_alter_chatmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='active_document_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
