# Generated by Django 6.0 on 2025-12-31 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0009_conversation_active_document_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='active_document_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='active_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_conversations', to='chatbotapp.document'),
        ),
    ]
