# Generated by Django 6.0 on 2026-01-02 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0010_remove_conversation_active_document_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='chatbotapp.document'),
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
